services:

  db:
    image: postgres:15-alpine
    container_name: blog_db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: blog_adminer
    ports:
      - "8084:8080"
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=blog_db

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: blog_app
    volumes:
      - ./app:/app
    ports:
      - "8008:8080"
    env_file:
      - .env.docker
    environment:
      APP_ENV: dev
      SERVER_NAME: :8080
      CADDY_MERCURE: "off"
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    depends_on:
      - db

  mailpit:
    image: axllent/mailpit:latest
    container_name: blog_mailpit
    ports:
      - "8028:8025"
      - "1028:1025"

volumes:
  dbdata: